name: dialer
description: A new Flutter project.
publish_to: "none"
version: 0.1.1+4

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1
  url_launcher: ^6.1.0
  shared_preferences: ^2.5.4
  http: ^1.6.0
  flutter_phone_direct_caller: ^2.2.1
  rflutter_alert: 2.0.7
  sqflite: ^2.3.3
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  motion_toast: ^2.15.0
  flutter_spinkit: ^5.2.2
  flutter_native_contact_picker:
 
  audioplayers: ^6.6.0
  geolocator: ^14.0.2
  camera: ^0.12.0
  path_provider: ^2.1.5
  just_audio:
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/call.png"